#!/usr/bin/env python
import sys
from signal import signal,SIGINT
from lib.window import Window
from gui.gui import GUI

if __name__ == '__main__':
    win = Window()
    gui = GUI(win)
    win.protocol("WM_DELETE_WINDOW",win.close)
    signal(SIGINT,win.close)
    win.launch()
